# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '29th-iOS-HW' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 29th-iOS-HW
  pod 'Alamofire', '~> 5.4'

  target '29th-iOS-HWTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '29th-iOS-HWUITests' do
    # Pods for testing
  end

end
